<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($collection->getSize()): ?>
<div class="mpblog-container">
    <h1 class="mp-title"><?php echo $this->getBlockHeader(); ?></h1>
    <div class="mpblog-list">
        <?php foreach ($this->getCollection() as $post): ?>
        <div class="mpblog-post">
            <h2 <?php if ($this->showThesis()): ?>class="mp-post-header"<?php endif; ?>><a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a></h2>
            <?php if ($this->showThesis()): ?>
            <div class="mp-header"><?php echo $this->getHeaderHtml($post); ?></div>
            <div class="mp-content std">
                <?php echo $post->getShortContent(); ?>
                <div class="mp-readmore"><a href="<?php echo $this->getReadMoreUrl($post); ?>">Read more...</a></div>
                <div class="mp-details"><?php echo $this->getFooterHtml($post); ?></div>
            </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
