<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<div class="mpblog-preview">
    <div class="mpblog-preview-header">
        <h1><?php echo $this->getHeader(); ?></h1>
    </div>
    <div class="mpblog-preview-content">
        <?php echo $this->getContent(); ?>
    </div>
</div>
<div class="mpblog-preview-button-set">
    <button style="" onclick="window.close(); return false;" class="button" type="button" title="<?php echo $this->__("Close"); ?>" id="preview-close"><span><span><?php echo $this->__("Close"); ?></span></span></button>
</div>
