<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <?php if($this->getLastPageNum()>1): ?>
    <div class="mp-pager">
        <div>
            <span class="navi older">
            <?php if (!$this->isFirstPage()): ?>
                <a class="older-link<?php if ($this->isOldStyle()): ?> old-style<?php endif; ?>" href="<?php echo $this->getPreviousPageUrl() ?>" rel="prev" title="<?php echo $this->__('Newer Entries') ?>"><i class="<?php echo $this->getColorClass(); ?> glyphicons chevron-left"></i><?php echo $this->__('Newer Entries') ?></a>
            <?php endif;?>
            </span>
            <span class="navi newer">
            <?php if (!$this->isLastPage()): ?>
                <a class="newer-link<?php if ($this->isOldStyle()): ?> old-style<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" rel="next" title="<?php echo $this->__('Older Entries') ?>"><?php echo $this->__('Older Entries') ?><i class="<?php echo $this->getColorClass(); ?> glyphicons chevron-right"></i></a>
            <?php endif;?>
            </span>
        </div>
        <div class="fixed"></div>
    </div>
    <?php endif; ?>
<?php endif ?>