<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();

/** @var Magpleasure_Blog_Model_Post $post  */
$post = $this->getPost();
?>
<?php if ($helper->getUseCategories()): ?>
    <?php echo $this->getCategoriesHtml(); ?>
<?php endif; ?>
<?php if ($helper->getUseTags()): ?>
<?php echo $this->getTagsHtml(); ?>
<?php endif; ?>
<div class="fixed"></div>