<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<?php /**  @var $this Magpleasure_Blog_Block_System_Config_Form_Element_Colors_Render */ ?>

<select class=" select" name="groups[tags][fields][presetted_colors][value]" id="mpblog_tags_presetted_colors">
<?php foreach ($this->getSchemes() as $value => $label): ?>
    <option  value="<?php echo $value; ?>"><?php echo $label; ?></option>
<?php endforeach; ?>
</select>

<button onclick="applyColorScheme();" class="scalable apply" type="button" title="<?php echo $this->__("Apply"); ?>" id="mpblog_tags_presetted_colors_apply">
    <span>
        <span>
            <span><?php echo $this->__("Apply"); ?></span>
        </span>
    </span>
</button>

<div class="fixed"></div>

<script type="text/javascript">

    var colorSchemes = <?php echo $this->getSchemesDataJson(); ?>;
    var applyColorScheme = function(){


        var key = $('mpblog_tags_presetted_colors').value;
        if (key){

            if (colorSchemes[key]){
                var data = colorSchemes[key];

                for (rowKey in data){
                    var id = 'mpblog_tags_mt_' + rowKey;
                    var element = $(id);
                    if (element){
                        element.value = data[rowKey];
                    }
                }
            }
        }

        return false;
    };

</script>