<div class="a">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_block_register_now')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('static_block_product')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_static_one')->toHtml() ?>
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_testimonials_block')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('four-columns-home')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('from_our_blog_block')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('static_block_product1')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('blog_slider')->toHtml() ?>
</div>
