<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && $collection->getSize()): ?>
<div class="block mpblog-recentposts">
    <div class="block-title">
        <strong><span><?php echo $this->getBlockHeader(); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="mplog-recent-posts">
        <?php foreach ($collection as $post): ?>
            <li class="mpblog-recent-post<?php if ($post->getIsActive()): ?> active<?php endif; ?> mpblog-recent-post-<?php echo $post->getId(); ?>">
                <i class="<?php echo $this->getColorClass(); ?> glyphicons ok_2"></i>
                <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                <?php if ($this->showDate()): ?>
                <div class="mp-recentpost-date">
                    <?php echo $this->renderDate($post->getCreatedAt()); ?>
                </div>
                <?php endif; ?>
                <?php if ($this->showThesis()): ?>
                <div class="mp-post-thesis">
                    <?php echo $this->getStrippedConent($post->getShortContent()); ?>
                </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
