<div class="row">
<div class="page-title-programe">
<h1 style="width:37%;"> Register for Aging Options Seminar </h1>
</div>
</div>

<form class="contact_form_events" onsubmit="return regSubmit()" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true);?>contact-us/index/agingseminar/" method="post">
     <div class="super-fieldset">
    <div class="fieldset">
       <div class="contact-form-left">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required">First Name</label>
                    <div class="input-box">
                        <input name="fname" type="text" id="txtFirstName" />
                    </div>
                </div>
			</li>	
			<li class="fields">	
                <div class="field">
                    <label for="name" class="required">Last Name</label>
                    <div class="input-box">
                        <input name="lname" type="text" id="txtLastName"/>
                    </div>
                </div>
            </li>	
         
		   
			
        </ul>
    </div>

	<div class="contact-form-right">
		 <ul class="form-list">
              <li class="fields">
			  <div class="field"> 
                <label for="telephone">Telephone</label>
                <div class="input-box">
                    <input name="telephone" type="text" id="txtPhone" onblur="isInteger();"/>
                </div>
			</div>	
            </li>
			
			 <li class="fields">
			  <div class="field">
					<label for="comment" class="required">Email</label>
					<div class="input-box">
						<input name="email" type="text"  id="txtEmail" onblur="checkEmail();"/>
					</div>
			  </div>		
            </li>
			
			
		</ul>	
	</div>
	
<div class="contact-form-bottom">	
	<ul>
	  <li class="fields">
			  <div class="field agingseminar-design-text">
					<label for="comment" class="required">Address</label>
					<div class="input-box agingseminar-design-box">
						<textarea cols="80" rows="5" id="address" name="address"></textarea>
					</div>
			  </div>		
      </li>
			
		
        </ul>
</div>

<div class="contact-form-left">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required">Country</label>
                    <div class="input-box">
                        <select name="country" id="country" style="width: 100%;">
						<option value="United States">United States</option>
						</select>
                    </div>
                </div>
			</li>	
			
         
		    <li class="fields">
			  <div class="field"> 
                <label for="telephone">City</label>
                <div class="input-box">
                    <input name="city" type="text" id="txtCity"/>
                </div>
			</div>	
            </li>
			
        </ul>
    </div>

	<div class="contact-form-right">
		 <ul class="form-list">
             <li class="fields">	
                <div class="field">
                    <label for="name" class="required">Zip/Postal Code</label>
                    <div class="input-box">
                        <input name="zip_code" type="text" id="txtZipCode"/>
                    </div>
                </div>
            </li>	
			
			 <li class="fields">
			  <div class="field">
					<label for="comment" class="required">State</label>
					<div class="input-box">
					<select name="state" style="width: 100%;">
						<option value="Alabama">Alabama</option>
						<option value="Alaska">Alaska</option>
						<option value="Arizona">Arizona</option>
						<option value="Arkansas">Arkansas</option>
						<option value="California">California</option>
						<option value="Colorado">Colorado</option>
						<option value="Connecticut">Connecticut</option>
						<option value="Delaware">Delaware</option>
						<option value="District of Columbia">District of Columbia</option>
						<option value="Florida">Florida</option>
						<option value="Georgia">Georgia</option>
						<option value="Hawaii">Hawaii</option>
						<option value="Idaho">Idaho</option>
						<option value="Illinois">Illinois</option>
						<option value="Indiana">Indiana</option>
						<option value="Iowa">Iowa</option>
						<option value="Kansas">Kansas</option>
						<option value="Kentucky">Kentucky</option>
						<option value="Louisiana">Louisiana</option>
						<option value="Maine">Maine</option>
						<option value="Maryland">Maryland</option>
						<option value="Massachusetts">Massachusetts</option>
						<option value="Michigan">Michigan</option>
						<option value="Minnesota">Minnesota</option>
						<option value="Mississippi">Mississippi</option>
						<option value="Missouri">Missouri</option>
						<option value="Montana">Montana</option>
						<option value="Nebraska">Nebraska</option>
						<option value="Nevada">Nevada</option>
						<option value="New Hampshire">New Hampshire</option>
						<option value="New Jersey">New Jersey</option>
						<option value="New Mexico">New Mexico</option>
						<option value="New York">New York</option>
						<option value="North Carolina">North Carolina</option>
						<option value="North Dakota">North Dakota</option>
						<option value="Ohio">Ohio</option>
						<option value="Oklahoma">Oklahoma</option>
						<option value="Oregon">Oregon</option>
						<option value="Pennsylvania">Pennsylvania</option>
						<option value="Rhode Island">Rhode Island</option>
						<option value="South Carolina">South Carolina</option>
						<option value="South Dakota">South Dakota</option>
						<option value="Tennessee">Tennessee</option>
						<option value="Texas">Texas</option>
						<option value="Utah">Utah</option>
						<option value="Vermont">Vermont</option>
						<option value="Virginia">Virginia</option>
						<option value="Washington">Washington</option>
						<option value="West Virginia">West Virginia</option>
						<option value="Wisconsin">Wisconsin</option>
						<option value="Wyoming">Wyoming</option>
					</select>
					</div>
			  </div>		
            </li>
			
			
		</ul>	
	</div>
	
	

	</div>
    <div class="buttons-set" style="width:96%"><div class="button-align-set">
        <button type="submit" class="button"><span><span>Submit</span></span></button>
    </div></div></div>
</form>

<script type="text/javascript">
function isInteger()
		{  
		var phone = document.getElementById("txtPhone");
		var filter = /^([a-zA-Z0-9])+$/;
			if (!filter.test(phone.value)) {
				
				phone.focus;
				return false;
			}
			else
			{
				return true;
			}
		}


		function checkEmail() {
			var email = document.getElementById('txtEmail');
			var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if (!filter.test(email.value)) {
				alert('Please provide a valid email address');
				//email.focus;
				return false;
			}
		}
		
		function regSubmit() {
			var errStr = "";
			if (document.getElementById("txtFirstName").value == "") errStr += "You must enter your first name.\r\n"
			if (document.getElementById("txtLastName").value == "") errStr += "You must enter your last name.\r\n"
			
			var validPhone= isInteger();
			
            /*if ((document.getElementById("txtPhone").value == "") || isNaN(document.getElementById("txtPhone").value) || !validPhone) errStr += "Please provide a valid 10 digit phone number.\r\n"*/

if (document.getElementById("txtPhone").value == "" || !validPhone) errStr += "Please provide valid phone number.\r\n"

			if (document.getElementById("txtEmail").value == "") errStr += "You must enter your email address.\r\n"
        
			
			var email = document.getElementById('txtEmail');
			var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if (!filter.test(email.value)) errStr += "Please provide a valid email address.\r\n";
			
			if (document.getElementById("address").value == "") errStr += "You must enter your address.\r\n"
			if (document.getElementById("txtZipCode").value == "") errStr += "You must enter your Zip Code.\r\n"
			if (document.getElementById("txtCity").value == "") errStr += "You must enter your City.\r\n"
			
			if (errStr != "") {
				if (errStr != "") alert(errStr);
				return false;
			}
		}
</script>