<div class="row">
<div class="page-title-programe">
<h1 style="width:31%;"> Contact Us</h1>
</div>
</div>
<h3> Any information sent through this contact form is not encrypted and therefore not secure. If you are a Longevity patient, please do not use this form to communicate with your doctor or clinic staff. We welcome calls regarding patient care at any of our three locations. <a style="color:#16386E" href="<?php echo Mage::getBaseUrl();?>locations">Click here</a> for contact information. Thank you.</h3>

<form class="contact_form_events" onsubmit="return regSubmit()" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true);?>contact-us/index/post/" method="post">
     <div class="super-fieldset">
    <div class="fieldset">
       <div class="contact-form-left">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required">First Name</label>
                    <div class="input-box">
                        <input name="fname" type="text" id="txtFirstName" />
                    </div>
                </div>
			</li>	
			
         
		    <li class="fields">
			  <div class="field"> 
                <label for="telephone">Telephone</label>
                <div class="input-box">
                    <input name="telephone" type="text" id="txtPhone" onblur="isInteger();"/>
                </div>
			</div>	
            </li>
			
        </ul>
    </div>

	<div class="contact-form-right">
		 <ul class="form-list">
             <li class="fields">	
                <div class="field">
                    <label for="name" class="required">Last Name</label>
                    <div class="input-box">
                        <input name="lname" type="text" id="txtLastName"/>
                    </div>
                </div>
            </li>	
			
			 <li class="fields">
			  <div class="field">
					<label for="comment" class="required">Email</label>
					<div class="input-box">
						<input name="email" type="text"  id="txtEmail" onblur="checkEmail();"/>
					</div>
			  </div>		
            </li>
			
			
		</ul>	
	</div>
	
<div class="contact-form-bottom">	
	<ul>
	  <li class="fields">
			  <div class="field">
					<label for="comment" class="required">Comments/Question</label>
					<div class="input-box">
						<textarea cols="80" rows="5" id="comments" name="comments"></textarea>
					</div>
			  </div>		
            </li>
			<span class="secure">Enter Numbers Below</span>
			<li class="fields">
			  <div class="field"  style="width:77%">

				<?php
				$num1 = rand(0,10); // pick a random number from 0 to 10 inclusive
				
				$num2 = rand(0,10); // same idea
				
				$o = rand(0,2); // 0 = plus, 1 = minus, 2 = multiply
				/* This function will use the integer value of $operand to show either a plus, minus, or times. */
				function operand($o) {
 				   switch($o) {
    					 case 0: return "+"; break;
   		       	   		 case 1: return "-"; break;
        				 case 2: return " x "; break;
      					default: return "?"; break; //Remark: We shouldn't ever get down here.
    					 }
					}
				?>

				<label for="math">
					<span style="font-size: 25px;">
						<?php $digits = 5; $captcha_num = rand(pow(10, $digits-1), pow(10, $digits)-1);echo $captcha_num; ?>
					</span>
 <?php //echo $num1 . "&nbsp;" . operand($o) . "&nbsp;" . $num2 . "?"; ?>
				</label>
				<div class="input-box">				
				<input type="text" id="math" name="userAnswer"></input>
				</div>
				<input type="hidden" id="number" value="<?php echo $captcha_num ?>"></input>
				<input type="hidden" id="num1" value="<?php echo $num1; ?>"></input>
				<input type="hidden" id="operand" value="<?php echo $o; ?>"></input>
				<input type="hidden" id="num2" value="<?php echo $num2; ?>"></input>
				</div></li>
		
        </ul>
</div>

	</div>
    <div class="buttons-set" style="width:96%"><div class="button-align-set">
        <button type="submit" class="button"><span><span>Submit</span></span></button>
    </div></div></div>
</form>


<script type="text/javascript">

		function isCaptcha(){
		
			var user_ans = document.getElementById("math").value;

			var num1 = document.getElementById("num1").value; 
			var num2 = document.getElementById("num2").value; 
			var o = document.getElementById("operand").value;
			var actual = -999;
			switch(parseInt(o)) {
    			case 0: actual = parseInt(num1) + parseInt(num2); break; // 0 = Addition
    			case 1: actual = parseInt(num1) - parseInt(num2); break; // 1 = Subtraction
    			case 2: actual = parseInt(num1) * parseInt(num2); break; // 2 = Multiplication
			}

			/* Check against the user's input and cancel form submission if it's incorrect */
			if(user_ans != actual) {
  			 return false;
			}
			else
			{
			 return true;	
			}


		}
		function isCaptchaValue(){
		
			var user_ans = document.getElementById("math").value;
			var actual = document.getElementById("number").value; 
			//alert(user_ans);alert(actual);	
			if(user_ans != actual) {
  			 return false; 
			}
			else
			{
			 return true;	
			}

		}
		function isInteger()
		{  
		var phone = document.getElementById("txtPhone");
		var filter = /^([a-zA-Z0-9])+$/;
			if (!filter.test(phone.value)) {
				
				phone.focus;
				return false;
			}
			else
			{
				return true;
			}
		}


		function checkEmail() {
			var email = document.getElementById('txtEmail');
			var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if (!filter.test(email.value)) {
				alert('Please provide a valid email address');
				//email.focus;
				return false;
			}
		}
		function regSubmit() {
			var errStr = "";
			if (document.getElementById("txtFirstName").value == "") errStr += "You must enter your first name.\r\n"
			if (document.getElementById("txtLastName").value == "") errStr += "You must enter your last name.\r\n"
			
			var validPhone= isInteger();
			
            /*if ((document.getElementById("txtPhone").value == "") || isNaN(document.getElementById("txtPhone").value) || !validPhone) errStr += "Please provide a valid 10 digit phone number.\r\n"*/

if (document.getElementById("txtPhone").value == "" || !validPhone) errStr += "Please provide valid phone number.\r\n"

			if (document.getElementById("txtEmail").value == "") errStr += "You must enter your email address.\r\n"
        
			//var captcha= isCaptcha();
			var captcha= isCaptchaValue();
			if (document.getElementById("math").value == "" || !captcha) {
			errStr += "Please provide correct value for captcha.\r\n";
				 }
			var email = document.getElementById('txtEmail');
			var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
			if (!filter.test(email.value)) errStr += "Please provide a valid email address.\r\n";
			if (errStr != "") {
				if (errStr != "") alert(errStr);
				return false;
			}
		}
	</script>
