<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<?php if ($this->isFacebookPlusEnabled()): ?>
<meta property="og:url" content="<?php echo $this->getPostUrl(); ?>" />
<meta property="og:type" content="website" />
<meta property="og:title" content="<?php echo $this->getPostTitle(); ?>" />
<meta property="og:description" content="<?php echo $this->getPostMetaDescription(); ?>" />
<?php endif; ?>

<?php if ($this->isGooglePlusEnabled()): ?>
<script type="text/javascript">
    $$('html').each(function(element){
        $(element).setAttribute('itemtype','http://schema.org/Blog');
    });
</script>
<meta itemprop="name" content="<?php echo $this->getPostTitle(); ?>">
<meta itemprop="description" content="<?php echo $this->getPostMetaDescription(); ?>">

<?php endif; ?>