<?php
	
	$_productCollection=$this->getData('products');
	$product_count=Mage::getStoreConfig('tab1/general/generalproducts');
 $_helper = $this->helper('catalog/output');
?>
<?php if(!count($_productCollection)):
 ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()=='grid'): ?>
    <?php $_iterator = 0; ?>
    <ul class="products-list" id="products-list">
    <?php $count=0; foreach ($_productCollection as $_product):if($count<$product_count){ ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div class="item-inner">
            <div class="row">
                <div class="col-sm-4 col-md-4 col-sms-4 col-smb-12">
					<div class="box-item">
						<?php
									$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
									$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();                 
									$now = date("Y-m-d H:m(worry)");
									// Get the Special Price
									$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
									// Get Current date
									if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
										echo "<span class='sale'>sale</span>";
										}else{
										if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
											echo "<span class='new'>new</span>";
											//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
										}
									}
								?>
                                <div class="products">
                                        <article class="product">
                                            <figure> 
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                        <div class="product-image">
                                                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>" width="270" height="270" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                        </div>
                                                        <div class="product-image image-rotator">
                                                                <?php 
                                                                $product = Mage::getModel('catalog/product')->load($_product->getId());
                                                                if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
                                                                        //$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
                                                                        $image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(270,270);
                                                                } else {
                                                                        $image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(270,270);
                                                                }
                                                                ?>
                                                                <img src="<?php echo $image ?>" width="270" height="270" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                         </div>			
                                                
                                                </a>
                                        </figure>
                                        </article>
                                </div>
					</div>
                </div>
            <?php // Product description ?>
            <div class="product-shop col-sm-8 col-md-8 col-sms-8 col-smb-12">
                <div class="f-fix">
                    <div class="list-box">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <div class="name-sale">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						<?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>
                        </div>
                        <div class="store-product-price"><?php $price=$_product->getPrice(); echo "$".number_format($price, 2); /*echo $this->getPriceHtml($_product, true)*/ ?></div>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <div class="actions">
                    <ul class="add-to-links">
                        <li>
                            <?php if($_product->isSaleable()):
				$_productId = $_product->getId();;
$_products = Mage::getModel('catalog/product')->load($_productId);
$_url = Mage::helper('checkout/cart')->getAddUrl($_products); ?>
                            <button type="button"  class="button btn-cart" onclick="setLocation('<?php echo $_url;/*echo $this->getAddToCartUrl($_product)*/ ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
						   
						  

                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        </li>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"   class="link-wishlist"><i class="fa fa-heart"></i><?php echo $this->__('Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><?php /*$_compareUrl= $this->helper('catalog/product_compare')->getAddUrl($_product); if($_compareUrl)*//*=$this->getAddToCompareUrl($_product))*//*:*/ ?>
                            <li><a href="<?php echo $_compareUrl ?>"  class="link-compare"><i class="fa fa-retweet"></i><?php echo $this->__('Compare') ?></a></li>
                        <?php endif; ?>
                        
                    </ul>
                    
                    </div>
                </div>
            </div>
            </div>
            </div>
        </li>
    <?php }
	else{
break;}
$count=$count+1; endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 4 ?>
    <?php $i=0;$count=0; foreach ($_productCollection as $_product): if($count<$product_count){?>
    <?php if ($i++%$_columnCount==0): ?>
    <div class="products-grid row">
    <?php endif ?>     
            <div class="col-sm-3 col-md-3 col-sms-3 col-smb-12 item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                    <div class="item-inner">                        
                            <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
						<div class="box-item">
							<?php
								$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
								$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();                 
								$now = date("Y-m-d H:m(worry)");
								// Get the Special Price
								$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
								// Get Current date
								if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
									echo "<span class='sale'>sale</span>";
									}else{
									if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
										echo "<span class='new'>new</span>";
										//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
									}
								}
							?>
                            <div class="products">
                                        <article class="product">
                                            <figure> 
                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                                        <div class="product-image">
                                                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>" width="270" height="270" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                        </div>
                                                        <div class="product-image image-rotator">
                                                                <?php 
                                                                $product = Mage::getModel('catalog/product')->load($_product->getId());
                                                                if ($product->getRotatorImage() && $product->getRotatorImage() !='no_selection') {
                                                                        //$imageTooltipResize = $this->getResizedUrl($imagetTooltip,600,400);
                                                                        $image = Mage::helper('catalog/image')->init($product, 'rotator_image')->resize(270, 270);
                                                                } else {
                                                                        $image = Mage::helper('catalog/image')->init($_product, 'small_image')->resize(270, 270);
                                                                }
                                                                ?>
                                                                <img src="<?php echo $image ?>" width="270" height="270" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                                         </div>			
                                                
                                                </a>
                                        </figure>
                                        </article>
                                    </div>
									<div class="box-link">
										<div class="actions">
												<?php if($_product->isSaleable()): 
$_productId = $_product->getId();;
$_products = Mage::getModel('catalog/product')->load($_productId);
$_url = Mage::helper('checkout/cart')->getAddUrl($_products);   ?>
													<!--<button type="button"  class="button btn-cart" onclick="setLocation('<?php echo $_url ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>-->
													
													   <button type="button"  class="button btn-cart" onclick="setLocation('<?php echo $_url;/*echo $this->getAddToCartUrl($_product)*/ ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
													
													<?php else: ?>
														<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php endif; ?>
												<ul class="add-to-links">
													<?php if ($this->helper('wishlist')->isAllow()) : ?>
														<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Wishlist') ?>"  class="link-wishlist"><i class="fa fa-heart"></i><?php echo $this->__('Wishlist') ?></a></li>
													<?php endif; ?>
					<?php //if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
     <?php $_compareUrl= $this->helper('catalog/product_compare')->getAddUrl($_product); if($_compareUrl): ?>
														<li><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Compare') ?>"  class="link-compare"><i class="fa fa-retweet"></i><?php echo $this->__('Compare') ?></a></li>
													<?php endif; ?>
												</ul>   
										</div>
									</div>
                            </div>
                            <h2 class="product-filter-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <div class="store-product-price"><?php $price=$_product->getPrice(); echo "$".number_format($price, 2); /*echo $this->getPriceHtml($_product, true)*/ ?></div>
                    </div>
            
            </div>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </div>
    <?php endif ?>
    <?php }
	else{
break;}
$count=$count+1;endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
