<div class="input-box-captcha">
    <input type="text" name="captcha_code" id="captcha_code" size="10" maxlength="5" class="input-text required-entry" />
	<img id="captcha" src="<?php $captcha_url=$this->getUrl('*/form/captcha'); echo str_replace('http','https',$captcha_url);?>" alt="CAPTCHA Image" />
    <a  class="refresh-captcha" style="border: none;" href="" title="refresh image" onclick="refresh_image(); return false;"><img src="<?php echo $this->getSkinUrl('images/testimonial/refresh.png')  ?>" alt="refresh image" border="0" onclick=""/></a>
    <br />
    <p><?php echo $this->__('Copy the text in the image above')?></p> 
</div> 
<script type="text/javascript">
	function refresh_image() {
		$('captcha').src = '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>';
		var new_image = '<?php $cap_url= $this->getUrl('*/form/captcha'); echo str_replace('http','https',$cap_url);?>' + Math.random();
		$('captcha').src = new_image;
	}
</script>
