<?php


  $collection = Mage::getModel("events/event")->getCollection();
	$event_data = $collection->getData();
	
  function my_compare($a, $b)
{
    $t1 = strtotime($a['event_date']);
    $t2 = strtotime($b['event_date']);
    return $t1 - $t2;
}   
usort($event_data, 'my_compare');
  
 foreach($event_data as $final_model)
{ 	

	
  $current_time= strtotime(date('Y-m-d H:i:s',strtotime('-8 hour')));
  $event_start_time= strtotime(date($final_model['event_start_date'].' '.$final_model['event_start_time']));
  $event_end_time=strtotime(date($final_model['event_end_date'].' '.$final_model['event_end_time']));

$isWebinar=$final_model['iswebinar'];

if($current_time>=$event_start_time)
{
	
	if($current_time<$event_end_time)
	{

		if($isWebinar) {

			echo '<div class="event-addres-new">';
			echo '<h4>'.$final_model['city'].'</h4>';
			echo '<ul>';
			echo '<li><span><i class="fa fa-calendar" aria-hidden="true"></i></span><span>'.date("l",strtotime($final_model['event_date'])).' '.date("M jS", strtotime($final_model['event_date'])).' - '.date("h:i a",strtotime($final_model['event_time'])).'</span></li>';
			echo '</div>';

		} else {

			echo '<div class="event-addres-new">';
			echo '<h4>'.$final_model['city'].'</h4>';
			echo '<ul>';
			echo '<li><span><i class="fa fa-calendar" aria-hidden="true"></i></span><span>'.date("l",strtotime($final_model['event_date'])).' '.date("M jS", strtotime($final_model['event_date'])).' - '.date("h:i a",strtotime($final_model['event_time'])).'</span></li>';
			echo ' <li><span><i class="fa fa-map-marker" aria-hidden="true"></i></span><span>'.$final_model['location'].'</span></li> <li>'.$final_model['street'].'<br/>'.$final_model['city'].' ,&nbsp;&nbsp; '.$final_model['state'].' &nbsp;&nbsp;'.$final_model['zipcode'].'</li> </ul>';
			echo '</div>';
		}	
	}
}

}   


  
?>

