<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Blog
 * @version    1.2.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();
?>
<?php if ($this->isBlogPage()):  ?>

    <?php if ($this->isCategoryPage() && $helper->getRssCatgeory()): ?>
        <link title="<?php echo $this->checkForPrefix($this->__("%s Feed", $this->getCategoryName())); ?>" href="<?php echo $this->getCategoryFeedUrl(); ?>" type="application/rss+xml" rel="alternate" />
    <?php else: ?>
        <?php if ($helper->getRssPost()): ?>
        <link title="<?php echo $this->checkForPrefix($this->__("Post Feed")); ?>" href="<?php echo $this->getPostFeedUrl(); ?>" type="application/rss+xml" rel="alternate" />
        <?php endif; ?>
    <?php endif;?>

    <?php if ($helper->getRssComment()): ?>
    <link title="<?php echo $this->checkForPrefix($this->__("Comment Feed")); ?>" href="<?php echo $this->getCommentFeedUrl(); ?>" type="application/rss+xml" rel="alternate" />
    <?php endif; ?>
<?php endif; ?>
